### PR TITLE
add workflow that automatically updates the release tag for libretranslate

### LINKED ISSUE #2: add workflow that automatically updates the release tag for libretranslate
See https://github.com/szaimen/aio-libretranslate/blob/9cd44a053061ca86a553955d22713717e3dd8523/.github/workflows/docker-build.yml#L25

### PR DESCRIPTION
**Pull request by Zoey2936**
Close https://github.com/szaimen/aio-libretranslate/issues/2

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Thanks and LGTM, lets see :)

**Comment by szaimen** [comment]
@Zoey2936 this does not seem to work. See https://github.com/szaimen/aio-libretranslate/actions/runs/7527127171/job/20486648320... Any idea?

**Comment by Zoey2936** [comment]
can you please retry, for me it worked: https://github.com/Zoey2936/aio-libretranslate/actions/runs/7519009826/job/20467037669

**Comment by szaimen** [comment]
Still doesnt work :/
https://github.com/szaimen/aio-libretranslate/actions/runs/7528559188

**Comment by Zoey2936** [comment]
can you please add `git fetch` to run before running git checkout $libre-version

**Comment by Zoey2936** [comment]
see #4

**Pull request merged**
